version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=1G
    environment:
      MYSQL_DATABASE: 'ehtp_rgph'
      MYSQL_USER: 'ehtp'
      MYSQL_PASSWORD: 'ehtp'
      MYSQL_ROOT_PASSWORD: 'ehtp'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ehtp
      MONGO_INITDB_ROOT_PASSWORD: ehtp
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mysql:
  mongodb: